# Generated by Django 4.0.3 on 2022-03-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SharpBargain', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DB_user',
        ),
        migrations.DeleteModel(
            name='Manufacturer',
        ),
        migrations.AddField(
            model_name='db_product',
            name='manu_address',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
    ]
