# Generated by Django 4.0.3 on 2022-04-01 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SharpBargain', '0002_delete_db_user_delete_manufacturer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='db_product',
            name='manu_address',
        ),
    ]
